"""
SQLAlchemy declarative base — ORM foundation.

Per docs/04-backend-architecture.md, Section 1 (Data Access Layer): every
future domain model (app/domains/*/models.py) inherits from the `Base`
defined here, so all 21 domains share one `MetaData` object and therefore
one consistent Alembic migration history (alembic/env.py imports this same
`Base.metadata` as its autogenerate target — see that file).

No domain entity is defined in this module. Per Prompt 9's explicit
exclusion list (MediaAsset, Memory, Game, UnlockCondition, Achievement,
Visitor, Letter, Timeline, and every other business table), this file
establishes ONLY the shared base class and naming convention future models
will use — implementing docs/03-data-architecture.md's entities is future
work, one domain at a time.
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# A consistent constraint-naming convention, applied to every table that
# inherits from Base. This matters specifically for Alembic autogenerate:
# without a fixed naming convention, SQLAlchemy lets the database assign
# default constraint names, which differ across runs/environments and
# produce noisy, inconsistent autogenerated migrations. Fixing the
# convention now — before any table exists — means every future domain's
# first migration is clean from the start rather than needing a later
# cleanup pass.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """
    Shared declarative base for every domain model.

    Per docs/04-backend-architecture.md, Section 1: only files inside
    app/domains/*/models.py (and, once implemented, their repository.py
    counterparts) should ever import this class — no API Layer or Service
    Layer code should import `Base` or any SQLAlchemy model directly.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
